name: 'chinook'
version: '1.0.0'
config-version: 2

profile: 'chinook'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"] 

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chinook_workshop:
    # Configurations for the "raw" layer
    raw:
      materialized: view
      +docs:
        node_color: "#CD7F32" # Bronze

    # Configurations for the "staging" layer
    staging:
      materialized: view
      +docs:
        node_color: "#C0C0C0" # Silver

    # Configurations for the "reports" layer
    reports:
      materialized: table
      +docs:
        node_color: "#FFD700" # Gold
